name: min_soft_ware
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  tdlib:
    path: ./packages/tdlib_min
  dio: ^5.2.1+1
  logger: ^1.4.0
  provider: ^6.0.5
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  path: ^1.8.0
  open_file: ^3.3.2
  file_picker: ^5.3.2
  file_selector: ^0.9.4
  rebirth: ^1.0.2
  intl: ^0.18.1
  flutter_easyloading: ^3.0.5
  path_provider: ^2.0.2
  fluttertoast: ^8.2.2
  flutter_spinkit: ^5.2.0
  pull_to_refresh: ^2.0.0
  retrofit: ^4.0.1
  permission_handler: ^8.3.0
  cupertino_icons: ^1.0.2
  get_it: ^7.6.0
  country_pickers: ^2.0.0
  pretty_qr_code: ^2.0.3
  http: ^1.1.0
  desktop_window: ^0.4.0
  easy_sidemenu: ^0.4.2
  url_launcher: ^6.1.11
  shared_preferences: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.7
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1





flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/image/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/image/logo.png"
    background_color: "#ffffff"
    icon_size: 48
    # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/image/logo.png"



flutter_gen:
  output: lib/src/gen/
  integrations:
    flutter_svg: true
flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/images/
    - assets/icons/

